/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.view;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Admin
 */
public class MainApplicationView extends javax.swing.JFrame {

    /**
     * Creates new form MainApplication
     */
    private SellPanel panelSell;
    private StaffPanel panelStaff;
    private ProductPanel panelProduct;
    private CustomerPanel customerPanel;
    private OrderPanel orderPanel;
    private DiscountPanel discountPanel;

    public MainApplicationView() {
        initComponents();
        panelSell = new SellPanel();
        panelStaff = new StaffPanel();
        panelProduct = new ProductPanel(this);
        customerPanel = new CustomerPanel();
        orderPanel = new OrderPanel();
        discountPanel = new DiscountPanel();
        this.onClicked(sellPanelBtn, sellStatusLb);
        showPanel(panelSell);
    }

//    private void showInfor(User user) {
//        labelShowOffice.setText("Chức Vụ: " + user.getOffice().getName());
//        labelShowName.setText("Tên: " + user.getMiddleName() + " " + user.getName());
//        txtAccount.setText(user.getEmail());
//        pswAccount.setText(user.getPassword());
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelControl = new javax.swing.JPanel();
        sellPanelBtn = new javax.swing.JPanel();
        sellLb = new javax.swing.JLabel();
        sellStatusLb = new javax.swing.JPanel();
        productPanelBtn = new javax.swing.JPanel();
        productLb = new javax.swing.JLabel();
        productStatusLb = new javax.swing.JPanel();
        staffPanelBtn = new javax.swing.JPanel();
        staffLb = new javax.swing.JLabel();
        staffStatusLb = new javax.swing.JPanel();
        orderPanelBtn = new javax.swing.JPanel();
        orderLb = new javax.swing.JLabel();
        orderStatusLb = new javax.swing.JPanel();
        discountPanelBtn = new javax.swing.JPanel();
        discountLb = new javax.swing.JLabel();
        discountStatusLb = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        exitLb = new javax.swing.JLabel();
        exitStatusLb = new javax.swing.JPanel();
        userPanelBtn = new javax.swing.JPanel();
        userLb = new javax.swing.JLabel();
        userStatusLb = new javax.swing.JPanel();
        statisticPanelBtn = new javax.swing.JPanel();
        statisticLb = new javax.swing.JLabel();
        statisticStatusLb = new javax.swing.JPanel();
        labelShowOffice = new javax.swing.JLabel();
        labelShowName = new javax.swing.JLabel();
        txtAccount = new app.view.swing.TextField();
        btnChangePass = new app.view.swing.Button();
        pswAccount = new app.view.swing.MyPass();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1428, 800));

        panelControl.setBackground(new java.awt.Color(23, 35, 51));
        panelControl.setPreferredSize(new java.awt.Dimension(175, 744));

        sellPanelBtn.setBackground(new java.awt.Color(23, 44, 76));
        sellPanelBtn.setPreferredSize(new java.awt.Dimension(163, 36));

        sellLb.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        sellLb.setForeground(new java.awt.Color(255, 255, 255));
        sellLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/content/online-store.png"))); // NOI18N
        sellLb.setText("BÁN HÀNG");
        sellLb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sellLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellLbMouseClicked(evt);
            }
        });

        sellStatusLb.setBackground(new java.awt.Color(255, 255, 255));
        sellStatusLb.setOpaque(false);
        sellStatusLb.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout sellStatusLbLayout = new javax.swing.GroupLayout(sellStatusLb);
        sellStatusLb.setLayout(sellStatusLbLayout);
        sellStatusLbLayout.setHorizontalGroup(
            sellStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        sellStatusLbLayout.setVerticalGroup(
            sellStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sellPanelBtnLayout = new javax.swing.GroupLayout(sellPanelBtn);
        sellPanelBtn.setLayout(sellPanelBtnLayout);
        sellPanelBtnLayout.setHorizontalGroup(
            sellPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sellPanelBtnLayout.createSequentialGroup()
                .addComponent(sellStatusLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sellPanelBtnLayout.setVerticalGroup(
            sellPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sellStatusLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(sellLb, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        productPanelBtn.setBackground(new java.awt.Color(23, 44, 76));
        productPanelBtn.setPreferredSize(new java.awt.Dimension(163, 36));

        productLb.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        productLb.setForeground(new java.awt.Color(255, 255, 255));
        productLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/content/product.png"))); // NOI18N
        productLb.setText("SẢN PHẨM");
        productLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productLbMouseClicked(evt);
            }
        });

        productStatusLb.setBackground(new java.awt.Color(255, 255, 255));
        productStatusLb.setOpaque(false);
        productStatusLb.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout productStatusLbLayout = new javax.swing.GroupLayout(productStatusLb);
        productStatusLb.setLayout(productStatusLbLayout);
        productStatusLbLayout.setHorizontalGroup(
            productStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        productStatusLbLayout.setVerticalGroup(
            productStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout productPanelBtnLayout = new javax.swing.GroupLayout(productPanelBtn);
        productPanelBtn.setLayout(productPanelBtnLayout);
        productPanelBtnLayout.setHorizontalGroup(
            productPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanelBtnLayout.createSequentialGroup()
                .addComponent(productStatusLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productPanelBtnLayout.setVerticalGroup(
            productPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productStatusLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(productLb, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        staffPanelBtn.setBackground(new java.awt.Color(23, 44, 76));
        staffPanelBtn.setPreferredSize(new java.awt.Dimension(163, 36));

        staffLb.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        staffLb.setForeground(new java.awt.Color(255, 255, 255));
        staffLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/content/staff.png"))); // NOI18N
        staffLb.setText("NHÂN VIÊN");
        staffLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffLbMouseClicked(evt);
            }
        });

        staffStatusLb.setBackground(new java.awt.Color(255, 255, 255));
        staffStatusLb.setOpaque(false);
        staffStatusLb.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout staffStatusLbLayout = new javax.swing.GroupLayout(staffStatusLb);
        staffStatusLb.setLayout(staffStatusLbLayout);
        staffStatusLbLayout.setHorizontalGroup(
            staffStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        staffStatusLbLayout.setVerticalGroup(
            staffStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout staffPanelBtnLayout = new javax.swing.GroupLayout(staffPanelBtn);
        staffPanelBtn.setLayout(staffPanelBtnLayout);
        staffPanelBtnLayout.setHorizontalGroup(
            staffPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffPanelBtnLayout.createSequentialGroup()
                .addComponent(staffStatusLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        staffPanelBtnLayout.setVerticalGroup(
            staffPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staffStatusLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(staffLb, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        orderPanelBtn.setBackground(new java.awt.Color(23, 44, 76));
        orderPanelBtn.setPreferredSize(new java.awt.Dimension(163, 36));

        orderLb.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        orderLb.setForeground(new java.awt.Color(255, 255, 255));
        orderLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/content/cargo.png"))); // NOI18N
        orderLb.setText("HÓA ĐƠN");
        orderLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderLbMouseClicked(evt);
            }
        });

        orderStatusLb.setBackground(new java.awt.Color(255, 255, 255));
        orderStatusLb.setOpaque(false);
        orderStatusLb.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout orderStatusLbLayout = new javax.swing.GroupLayout(orderStatusLb);
        orderStatusLb.setLayout(orderStatusLbLayout);
        orderStatusLbLayout.setHorizontalGroup(
            orderStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        orderStatusLbLayout.setVerticalGroup(
            orderStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout orderPanelBtnLayout = new javax.swing.GroupLayout(orderPanelBtn);
        orderPanelBtn.setLayout(orderPanelBtnLayout);
        orderPanelBtnLayout.setHorizontalGroup(
            orderPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelBtnLayout.createSequentialGroup()
                .addComponent(orderStatusLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orderPanelBtnLayout.setVerticalGroup(
            orderPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderStatusLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(orderLb, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        discountPanelBtn.setBackground(new java.awt.Color(23, 44, 76));
        discountPanelBtn.setPreferredSize(new java.awt.Dimension(163, 36));

        discountLb.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        discountLb.setForeground(new java.awt.Color(255, 255, 255));
        discountLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/content/discount.png"))); // NOI18N
        discountLb.setText("KHUYẾN MÃI");
        discountLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                discountLbMouseClicked(evt);
            }
        });

        discountStatusLb.setBackground(new java.awt.Color(255, 255, 255));
        discountStatusLb.setOpaque(false);
        discountStatusLb.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout discountStatusLbLayout = new javax.swing.GroupLayout(discountStatusLb);
        discountStatusLb.setLayout(discountStatusLbLayout);
        discountStatusLbLayout.setHorizontalGroup(
            discountStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        discountStatusLbLayout.setVerticalGroup(
            discountStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout discountPanelBtnLayout = new javax.swing.GroupLayout(discountPanelBtn);
        discountPanelBtn.setLayout(discountPanelBtnLayout);
        discountPanelBtnLayout.setHorizontalGroup(
            discountPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, discountPanelBtnLayout.createSequentialGroup()
                .addComponent(discountStatusLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discountLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        discountPanelBtnLayout.setVerticalGroup(
            discountPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(discountStatusLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(discountLb, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(23, 44, 76));
        jPanel12.setPreferredSize(new java.awt.Dimension(163, 36));

        exitLb.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        exitLb.setForeground(new java.awt.Color(255, 255, 255));
        exitLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/content/logout.png"))); // NOI18N
        exitLb.setText("THOÁT");
        exitLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLbMouseClicked(evt);
            }
        });

        exitStatusLb.setBackground(new java.awt.Color(255, 255, 255));
        exitStatusLb.setOpaque(false);
        exitStatusLb.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout exitStatusLbLayout = new javax.swing.GroupLayout(exitStatusLb);
        exitStatusLb.setLayout(exitStatusLbLayout);
        exitStatusLbLayout.setHorizontalGroup(
            exitStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        exitStatusLbLayout.setVerticalGroup(
            exitStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addComponent(exitStatusLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitStatusLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(exitLb, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        userPanelBtn.setBackground(new java.awt.Color(23, 44, 76));
        userPanelBtn.setPreferredSize(new java.awt.Dimension(163, 36));

        userLb.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        userLb.setForeground(new java.awt.Color(255, 255, 255));
        userLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/content/user.png"))); // NOI18N
        userLb.setText("KHÁCH HÀNG");
        userLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLbMouseClicked(evt);
            }
        });

        userStatusLb.setBackground(new java.awt.Color(255, 255, 255));
        userStatusLb.setOpaque(false);
        userStatusLb.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout userStatusLbLayout = new javax.swing.GroupLayout(userStatusLb);
        userStatusLb.setLayout(userStatusLbLayout);
        userStatusLbLayout.setHorizontalGroup(
            userStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        userStatusLbLayout.setVerticalGroup(
            userStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout userPanelBtnLayout = new javax.swing.GroupLayout(userPanelBtn);
        userPanelBtn.setLayout(userPanelBtnLayout);
        userPanelBtnLayout.setHorizontalGroup(
            userPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelBtnLayout.createSequentialGroup()
                .addComponent(userStatusLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLb, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        userPanelBtnLayout.setVerticalGroup(
            userPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userStatusLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(userLb, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        statisticPanelBtn.setBackground(new java.awt.Color(23, 44, 76));
        statisticPanelBtn.setPreferredSize(new java.awt.Dimension(163, 36));

        statisticLb.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        statisticLb.setForeground(new java.awt.Color(255, 255, 255));
        statisticLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/content/description.png"))); // NOI18N
        statisticLb.setText("THỐNG KÊ");
        statisticLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statisticLbMouseClicked(evt);
            }
        });

        statisticStatusLb.setBackground(new java.awt.Color(255, 255, 255));
        statisticStatusLb.setOpaque(false);
        statisticStatusLb.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout statisticStatusLbLayout = new javax.swing.GroupLayout(statisticStatusLb);
        statisticStatusLb.setLayout(statisticStatusLbLayout);
        statisticStatusLbLayout.setHorizontalGroup(
            statisticStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        statisticStatusLbLayout.setVerticalGroup(
            statisticStatusLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout statisticPanelBtnLayout = new javax.swing.GroupLayout(statisticPanelBtn);
        statisticPanelBtn.setLayout(statisticPanelBtnLayout);
        statisticPanelBtnLayout.setHorizontalGroup(
            statisticPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statisticPanelBtnLayout.createSequentialGroup()
                .addComponent(statisticStatusLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statisticLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statisticPanelBtnLayout.setVerticalGroup(
            statisticPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statisticStatusLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(statisticLb, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        labelShowOffice.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        labelShowOffice.setForeground(new java.awt.Color(255, 255, 255));
        labelShowOffice.setText("Chức Vụ");

        labelShowName.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        labelShowName.setForeground(new java.awt.Color(255, 255, 255));
        labelShowName.setText("Tên");

        txtAccount.setEditable(false);
        txtAccount.setBackground(new java.awt.Color(23, 35, 51));
        txtAccount.setForeground(new java.awt.Color(255, 255, 255));
        txtAccount.setLabelText("Tài Khoản");

        btnChangePass.setBackground(new java.awt.Color(51, 102, 255));
        btnChangePass.setText("Đổi Mật Khẩu");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        pswAccount.setBackground(new java.awt.Color(23, 35, 51));
        pswAccount.setForeground(new java.awt.Color(255, 255, 255));
        pswAccount.setLabelText("Mật Khẩu");

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sellPanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addComponent(productPanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addComponent(staffPanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addComponent(orderPanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addComponent(discountPanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addComponent(userPanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addComponent(statisticPanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelShowOffice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelShowName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelControlLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pswAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelControlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelShowOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelShowName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pswAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sellPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(staffPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(discountPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statisticPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        mainPanel.setAutoscrolls(true);
        mainPanel.setPreferredSize(new java.awt.Dimension(1373, 800));
        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelControl, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sellLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellLbMouseClicked
        this.onClicked(sellPanelBtn, sellStatusLb);
        this.unClicked(orderPanelBtn, orderStatusLb);
        this.unClicked(productPanelBtn, productStatusLb);
        this.unClicked(staffPanelBtn, staffStatusLb);
        this.unClicked(staffPanelBtn, staffStatusLb);
        this.unClicked(userPanelBtn, userStatusLb);
        this.unClicked(discountPanelBtn, discountStatusLb);
        showPanel(panelSell);
    }//GEN-LAST:event_sellLbMouseClicked

    private void productLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productLbMouseClicked
        this.onClicked(productPanelBtn, productStatusLb);
        this.unClicked(orderPanelBtn, orderStatusLb);
        this.unClicked(sellPanelBtn, sellStatusLb);
        this.unClicked(statisticPanelBtn, statisticStatusLb);
        this.unClicked(staffPanelBtn, staffStatusLb);
        this.unClicked(userPanelBtn, userStatusLb);
        this.unClicked(discountPanelBtn, discountStatusLb);
        showPanel(panelProduct);
    }//GEN-LAST:event_productLbMouseClicked

    private void staffLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffLbMouseClicked
        if (panelStaff == null) {
            JOptionPane.showMessageDialog(this, "Bạn Không Có Quyền Truy Cập Vào Mục Này");
            return;
        }
        this.onClicked(staffPanelBtn, staffStatusLb);
        this.unClicked(orderPanelBtn, orderStatusLb);
        this.unClicked(sellPanelBtn, sellStatusLb);
        this.unClicked(statisticPanelBtn, statisticStatusLb);
        this.unClicked(productPanelBtn, productStatusLb);
        this.unClicked(userPanelBtn, userStatusLb);
        this.unClicked(discountPanelBtn, discountStatusLb);
        showPanel(panelStaff);
    }//GEN-LAST:event_staffLbMouseClicked

    private void orderLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLbMouseClicked
        this.onClicked(orderPanelBtn, orderStatusLb);
        this.unClicked(productPanelBtn, productStatusLb);
        this.unClicked(sellPanelBtn, sellStatusLb);
        this.unClicked(statisticPanelBtn, statisticStatusLb);
        this.unClicked(staffPanelBtn, staffStatusLb);
        this.unClicked(userPanelBtn, userStatusLb);
        this.unClicked(discountPanelBtn, discountStatusLb);
        showPanel(orderPanel);
    }//GEN-LAST:event_orderLbMouseClicked

    private void discountLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discountLbMouseClicked
        this.onClicked(discountPanelBtn, discountStatusLb);
        this.unClicked(orderPanelBtn, orderStatusLb);
        this.unClicked(sellPanelBtn, sellStatusLb);
        this.unClicked(statisticPanelBtn, statisticStatusLb);
        this.unClicked(staffPanelBtn, staffStatusLb);
        this.unClicked(userPanelBtn, userStatusLb);
        this.unClicked(productPanelBtn, productStatusLb);
        showPanel(discountPanel);
    }//GEN-LAST:event_discountLbMouseClicked

    private void userLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLbMouseClicked
        this.onClicked(userPanelBtn, userStatusLb);
        this.unClicked(orderPanelBtn, orderStatusLb);
        this.unClicked(sellPanelBtn, sellStatusLb);
        this.unClicked(statisticPanelBtn, statisticStatusLb);
        this.unClicked(staffPanelBtn, staffStatusLb);
        this.unClicked(discountPanelBtn, discountStatusLb);
        this.unClicked(productPanelBtn, productStatusLb);
        showPanel(customerPanel);
    }//GEN-LAST:event_userLbMouseClicked

    private void statisticLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticLbMouseClicked
        JOptionPane.showMessageDialog(this, "Chưa Phát Triển");
    }//GEN-LAST:event_statisticLbMouseClicked

    private void exitLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLbMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLbMouseClicked

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        String pass = "";
        if (pswAccount.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mật Khẩu Không Được Để Trống");
        } else {
            if (pswAccount.getText().length() <= 5) {
                JOptionPane.showMessageDialog(this, "Mật Khẩu Phải Trên 6 Ký Tự");
            } else {
                pass = String.valueOf(pswAccount.getPassword());
            }
        }

        int agreeChange = JOptionPane.showConfirmDialog(this, "Bạn Có Chắc Chắn Muốn Đổi Mật Khẩu Không ?", "Xác Nhận", JOptionPane.YES_NO_OPTION);
//        if (agreeChange == JOptionPane.YES_OPTION) {
////            String staffCode = user.getCode();
//            boolean changeSuccess = service.changePassword(staffCode, pass);
//            if (changeSuccess) {
//                JOptionPane.showMessageDialog(this, "Đổi Password thành công !");
//            } else {
//                JOptionPane.showMessageDialog(this, "Đổi Password không thành công !");
//            }
//        }
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void onClicked(JPanel panelBackGroud, JPanel panelStatus) {
        panelBackGroud.setBackground(new Color(41, 64, 115));
        panelStatus.setOpaque(true);
    }

    private void unClicked(JPanel panelBackGroud, JPanel panelStatus) {
        panelBackGroud.setBackground(new Color(23, 44, 76));
        panelStatus.setOpaque(false);
    }

    private void showPanel(JPanel panel) {
        mainPanel.removeAll();
        mainPanel.add(panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new MainApplicationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.view.swing.Button btnChangePass;
    private javax.swing.JLabel discountLb;
    private javax.swing.JPanel discountPanelBtn;
    private javax.swing.JPanel discountStatusLb;
    private javax.swing.JLabel exitLb;
    private javax.swing.JPanel exitStatusLb;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JLabel labelShowName;
    private javax.swing.JLabel labelShowOffice;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel orderLb;
    private javax.swing.JPanel orderPanelBtn;
    private javax.swing.JPanel orderStatusLb;
    private javax.swing.JPanel panelControl;
    private javax.swing.JLabel productLb;
    private javax.swing.JPanel productPanelBtn;
    private javax.swing.JPanel productStatusLb;
    private app.view.swing.MyPass pswAccount;
    private javax.swing.JLabel sellLb;
    private javax.swing.JPanel sellPanelBtn;
    private javax.swing.JPanel sellStatusLb;
    private javax.swing.JLabel staffLb;
    private javax.swing.JPanel staffPanelBtn;
    private javax.swing.JPanel staffStatusLb;
    private javax.swing.JLabel statisticLb;
    private javax.swing.JPanel statisticPanelBtn;
    private javax.swing.JPanel statisticStatusLb;
    private app.view.swing.TextField txtAccount;
    private javax.swing.JLabel userLb;
    private javax.swing.JPanel userPanelBtn;
    private javax.swing.JPanel userStatusLb;
    // End of variables declaration//GEN-END:variables
}
