/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.view;

import app.service.NhanVienService;
import app.model.NhanVien;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import app.view.swing.EventPagination;
import app.view.swing.PaginationItemRenderStyle1;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Admin
 */
public class StaffPanel extends javax.swing.JPanel {

    NhanVienService nvService = new NhanVienService();
    DefaultTableModel tblmol = new DefaultTableModel();
    int index = -1;
    NhanVien nv = new NhanVien();
    List<NhanVien> listPhanTrangNhanVien = new ArrayList<>();
    private int currentpage = 1;

    public StaffPanel() {
        initComponents();
        index = 1;
//        fillTable(nvService.getAll());
//          tblmol = (DefaultTableModel)tblDisplay.getModel();
        pn.setPaginationItemRender(new PaginationItemRenderStyle1());
        pn.addEventPagination(new EventPagination() {
            @Override
            public void pageChanged(int page) {
                loadDataTablePhanTrang(page);
            }
        });
        loadDataTablePhanTrang(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGender = new javax.swing.ButtonGroup();
        btnGroupOffice = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        txtSearch = new app.view.swing.TextField();
        labelFullName1 = new javax.swing.JLabel();
        btnExport = new app.view.swing.Button();
        button2 = new app.view.swing.Button();
        jPanel1 = new javax.swing.JPanel();
        txtFullName = new app.view.swing.TextField();
        labelFullName = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new app.view.swing.TextField();
        rdFemale = new radio_button.RadioButtonCustom();
        rdMale = new radio_button.RadioButtonCustom();
        labelGender = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        txtAddress = new app.view.swing.TextField();
        labelEmail = new javax.swing.JLabel();
        txtEmail = new app.view.swing.TextField();
        rdStaff = new radio_button.RadioButtonCustom();
        labelOffice = new javax.swing.JLabel();
        rdManager = new radio_button.RadioButtonCustom();
        btnAdd = new app.view.swing.Button();
        btnNew = new app.view.swing.Button();
        btnChangeStatus = new app.view.swing.Button();
        btnUpdate = new app.view.swing.Button();
        labelAddressError = new javax.swing.JLabel();
        labelDateError = new javax.swing.JLabel();
        labelPhoneError = new javax.swing.JLabel();
        labelNameError = new javax.swing.JLabel();
        labelEmailError = new javax.swing.JLabel();
        txtCodeStaff = new app.view.swing.TextField();
        txtDate = new com.toedter.calendar.JDateChooser();
        pn = new app.view.swing.Pagination();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1418, 731));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Nhân Viên"));

        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Họ Tên", "Email", "Ngày Sinh", "Giới tính", "Vai trò", "So dt", "Deleted"
            }
        ));
        tblDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisplayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDisplay);

        txtSearch.setLabelText("");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        labelFullName1.setText("Họ và Tên");

        btnExport.setBackground(new java.awt.Color(0, 0, 0));
        btnExport.setForeground(new java.awt.Color(255, 255, 255));
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(0, 0, 0));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("Import");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Nhân Viên"));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        txtFullName.setLabelText("");

        labelFullName.setText("Họ và Tên");

        labelDate.setText("Ngày Sinh");

        labelPhoneNumber.setText("Số Điện Thoại");

        txtPhoneNumber.setLabelText("");

        rdFemale.setBackground(new java.awt.Color(51, 153, 255));
        btnGroupGender.add(rdFemale);
        rdFemale.setText("Nữ");

        rdMale.setBackground(new java.awt.Color(51, 153, 255));
        btnGroupGender.add(rdMale);
        rdMale.setSelected(true);
        rdMale.setText("Nam");

        labelGender.setText("Giới Tính");

        labelAddress.setText("Địa Chỉ");

        txtAddress.setLabelText("");

        labelEmail.setText("Email");

        txtEmail.setLabelText("");

        rdStaff.setBackground(new java.awt.Color(51, 153, 255));
        btnGroupOffice.add(rdStaff);
        rdStaff.setSelected(true);
        rdStaff.setText("Nhân Viên");

        labelOffice.setText("Chức Vụ");

        rdManager.setBackground(new java.awt.Color(51, 153, 255));
        btnGroupOffice.add(rdManager);
        rdManager.setText("Quản Lý");

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnNew.setBackground(new java.awt.Color(0, 0, 0));
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnChangeStatus.setBackground(new java.awt.Color(0, 0, 0));
        btnChangeStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeStatus.setText("Đổi Trạng Thái");
        btnChangeStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangeStatusMouseClicked(evt);
            }
        });
        btnChangeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStatusActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        labelAddressError.setForeground(new java.awt.Color(255, 51, 51));
        labelAddressError.setPreferredSize(new java.awt.Dimension(0, 15));

        labelDateError.setForeground(new java.awt.Color(255, 51, 51));
        labelDateError.setPreferredSize(new java.awt.Dimension(0, 15));

        labelPhoneError.setForeground(new java.awt.Color(255, 51, 51));
        labelPhoneError.setPreferredSize(new java.awt.Dimension(0, 15));

        labelNameError.setForeground(new java.awt.Color(255, 51, 51));
        labelNameError.setPreferredSize(new java.awt.Dimension(0, 15));

        labelEmailError.setForeground(new java.awt.Color(255, 51, 51));
        labelEmailError.setPreferredSize(new java.awt.Dimension(0, 15));

        txtCodeStaff.setEditable(false);
        txtCodeStaff.setLabelText("Mã Nhân Viên");
        txtCodeStaff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodeStaffKeyReleased(evt);
            }
        });

        txtDate.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdMale, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(rdFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDateError, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodeStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(166, 166, 166)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(rdStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdManager, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelAddressError, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelEmailError, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelPhoneError, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(155, 155, 155)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCodeStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAddressError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(labelEmailError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelOffice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rdStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNameError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rdMale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdFemale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDateError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPhoneError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChangeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelFullName1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(547, 547, 547)
                .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelFullName1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(565, 565, 565)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

    }//GEN-LAST:event_btnAddActionPerformed

    private void tblDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayMouseClicked
        index = tblDisplay.getSelectedRow();
        this.showData(index);
    }//GEN-LAST:event_tblDisplayMouseClicked

    private void btnChangeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStatusActionPerformed

    }//GEN-LAST:event_btnChangeStatusActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (checkTrung()&&checkTrung1()) {
        int a = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn Sửa?", "Sửa", JOptionPane.YES_NO_OPTION);
        index = tblDisplay.getSelectedRow();
        int id = Integer.parseInt(tblDisplay.getValueAt(index, 0).toString());
        if (validates()) {
            NhanVien nv = readForm();
            if (a == JOptionPane.YES_OPTION) {
                if (nvService.updateSV(nv, id) > 0) {
                    JOptionPane.showMessageDialog(this, "update thanh cong");
                    loadDataTablePhanTrang(1);
                } else {
                    JOptionPane.showMessageDialog(this, "update that bai");
                }
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed
    }
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed

        txtCodeStaff.setText(" ");
        txtDate.setDate(null);
        txtEmail.setText(" ");
        txtFullName.setText(" ");
        txtPhoneNumber.setText(" ");

    }//GEN-LAST:event_btnNewActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed

    }//GEN-LAST:event_btnExportActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        if (checkTrung()&&checkTrung1()) {
        int a = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn thêm?", "thêm", JOptionPane.YES_NO_OPTION);

        if (validates()) {
            NhanVien sv = this.readForm();
            if (a == JOptionPane.YES_OPTION) {
                if (nvService.addStudent(sv) > 0) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    loadDataTablePhanTrang(1);
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                }
            }

        }
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked

    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnChangeStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeStatusMouseClicked
        int a = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?", "remove", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            int row = tblDisplay.getSelectedRow();
            int id = Integer.parseInt(txtCodeStaff.getText());

            nvService.Delete(id);
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            loadDataTablePhanTrang(1);
            System.out.println(currentpage);

    }//GEN-LAST:event_btnChangeStatusMouseClicked
    }
    private void txtCodeStaffKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeStaffKeyReleased

    }//GEN-LAST:event_txtCodeStaffKeyReleased

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String textSearch = txtSearch.getText().toLowerCase().trim();
        System.out.println(textSearch);
        List<NhanVien> list = nvService.getAll();
        List<NhanVien> listSearch = new ArrayList<>();

        for (NhanVien nhanhnVien : list) {

            if (nhanhnVien.getTen().toLowerCase().contains(textSearch)) {
                listSearch.add(nhanhnVien);
            }
        }

        if (listSearch.isEmpty()) {
            fillTable(nvService.getAll());
        } else {
            if (txtSearch.getText().equals("")) {
                clearTable(tblmol);
                fillTable(list);
            } else {
                clearTable(tblmol);
                for (NhanVien nhanVien : listSearch) {
                    tblmol.addRow(nhanVien.toDataRow());
                }
                fillTable(listSearch);
            }
        }
    }//GEN-LAST:event_txtSearchKeyReleased
    public void fillTable(List<NhanVien> list) {
//        tblmol = (DefaultTableModel) tblDisplay.getModel();
        tblmol.setRowCount(0);
        for (NhanVien item : list) {

            tblmol.addRow(new Object[]{item.getID(), item.getTen(), item.getEmail(), item.getNgaySinh(), item.isGender() == true ? "Nam" : "Nữ", item.isRoLe() == true ? "Nhân viên" : "Quản Lý", item.getSdt(), item.isDeleted() == true ? "Đang hoạt động" : "Dừng hoạt động"});
        }
    }

    public void showData(int index) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        NhanVien nv = nvService.getAll().get(index);
        String ngaySinhString = dateFormat.format(nv.getNgaySinh());

        txtCodeStaff.setText(nv.getID().toString());
        txtFullName.setText(nv.getTen());
        txtAddress.setText(nv.getDiaChi());
        txtEmail.setText(nv.getEmail());
        txtPhoneNumber.setText(nv.getSdt());
        txtDate.setDate(nv.getNgaySinh());
        if (nv.isGender()) {
            rdMale.setSelected(true);
        } else {
            rdFemale.setSelected(true);
        }
        if (nv.isRoLe()) {
            rdStaff.setSelected(true);
        } else {
            rdManager.setSelected(true);
        }
    }

    private void clearTable(DefaultTableModel tblmol) {
        while (tblmol.getRowCount() > 0) {
            tblmol.removeRow(0);
        }
    }

    public NhanVien readForm() {

        try {
            int id;
            Date NgaySinh;
            String Ten, Email, DiaChi, Sdt;
            boolean Gender, Role;
            if (rdMale.isSelected()) {
                Gender = true;
            } else {
                Gender = false;
            }
            if (rdStaff.isSelected()) {
                Role = true;
            } else {
                Role = false;
            }
            id = Integer.parseInt(txtCodeStaff.getText());
            Ten = txtFullName.getText();
            Email = txtEmail.getText();
            NgaySinh = txtDate.getDate();
            DiaChi = txtAddress.getText();
            Sdt = txtPhoneNumber.getText();
            Date dateOfBirth = null;
//            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//            dateOfBirth = dateFormat.parse(NgaySinh+"");
            return new NhanVien(id, Ten, NgaySinh, Email, Gender, Role, Sdt, DiaChi);

        } catch (Exception ex) {
            Logger.getLogger(StaffPanel.class.getName()).log(Level.SEVERE, null, ex);
            return NhanVien();

        }

    }

    public void loadDataTablePhanTrang(int page) {
        int limit = 5;
        int offset = (page - 1) * limit;
        try {
            tblmol = (DefaultTableModel) tblDisplay.getModel();
            tblmol.setRowCount(0);
            fillTable(nvService.getAll());
            int count = nvService.count();
            System.out.println(count);
            int sumPage = (int) Math.ceil((double) count / limit);
            System.out.println(sumPage);
            listPhanTrangNhanVien = nvService.getListPhanTrang(offset, limit);
            fillTable(listPhanTrangNhanVien);
            pn.setPagegination(page, sumPage);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public boolean validates() {
        if (txtAddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Địa chỉ trống");
            txtAddress.requestFocus();
            return false;
        }
        if (txtFullName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên trống");
            txtFullName.requestFocus();
            return false;
        }
        if (txtPhoneNumber.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số điện thoại trống");
            txtPhoneNumber.requestFocus();
            return false;
        }
        String phoneRegex = "^(0[3|5|7|8|9])+([0-9]{8})$";

        Pattern pattern = Pattern.compile(phoneRegex);
        Matcher matcher = pattern.matcher(txtPhoneNumber.getText());

        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải đúng định dạng");
            txtPhoneNumber.requestFocus();
            return false;
        }
        if (txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email trống");
            txtPhoneNumber.requestFocus();
            return false;
        }
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."
                + "[a-zA-Z0-9_+&*-]+)*@"
                + "(?:[a-zA-Z0-9-]+\\.)+[a-z"
                + "A-Z]{2,7}$";

        Pattern pat = Pattern.compile(emailRegex);
        if (!pat.matcher(txtEmail.getText().trim()).matches()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng email");
            txtEmail.requestFocus();
            return false;
        }

        return true;
    }
boolean checkTrung() {
        List<NhanVien> lstXM = listPhanTrangNhanVien;
        for (int i = 0; i < lstXM.size(); i++) {
            if (txtPhoneNumber.getText().equalsIgnoreCase(lstXM.get(i).getSdt())) {
                JOptionPane.showMessageDialog(this, "Trùng số điện thoại");
                return false;
            }
        }
        return true;
    }
  boolean checkTrung1() {
        List<NhanVien> lstXM = listPhanTrangNhanVien;
        for (int i = 0; i < lstXM.size(); i++) {
            if (txtEmail.getText().equalsIgnoreCase(lstXM.get(i).getEmail())) {
                JOptionPane.showMessageDialog(this, "Trùng gmail");
                return false;
            }
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.view.swing.Button btnAdd;
    private app.view.swing.Button btnChangeStatus;
    private app.view.swing.Button btnExport;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.ButtonGroup btnGroupOffice;
    private app.view.swing.Button btnNew;
    private app.view.swing.Button btnUpdate;
    private app.view.swing.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelAddressError;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDateError;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmailError;
    private javax.swing.JLabel labelFullName;
    private javax.swing.JLabel labelFullName1;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelNameError;
    private javax.swing.JLabel labelOffice;
    private javax.swing.JLabel labelPhoneError;
    private javax.swing.JLabel labelPhoneNumber;
    private app.view.swing.Pagination pn;
    private radio_button.RadioButtonCustom rdFemale;
    private radio_button.RadioButtonCustom rdMale;
    private radio_button.RadioButtonCustom rdManager;
    private radio_button.RadioButtonCustom rdStaff;
    private javax.swing.JTable tblDisplay;
    private app.view.swing.TextField txtAddress;
    private app.view.swing.TextField txtCodeStaff;
    private com.toedter.calendar.JDateChooser txtDate;
    private app.view.swing.TextField txtEmail;
    private app.view.swing.TextField txtFullName;
    private app.view.swing.TextField txtPhoneNumber;
    private app.view.swing.TextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private NhanVien NhanVien() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
