package app.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import app.model.Statistical;
import app.service.StatisticalService;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Frame;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.io.FileExistsException;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author NGUYỄN ĐỨC LƯƠNG
 */
public class StatisticalPanel extends javax.swing.JPanel {

    private DefaultTableModel dtm = new DefaultTableModel();
    private Statistical ss = new Statistical();
    private StatisticalService sts = new StatisticalService();

    /**
     * Creates new form StatisticalPanel3
     */
    public StatisticalPanel() {
        initComponents();
        dtm = (DefaultTableModel) tbHienThi.getModel();
        loadTable();
        tongNam();
        tongThang();
    }

    public void loadTable() {
        dtm.setRowCount(0);
        ArrayList<Statistical> list = sts.getList();
        for (Statistical s : list) {
            dtm.addRow(new Object[]{s.getThang(), s.getTen(), s.getSoLuong(), new BigDecimal(s.getTongTien())});
        }
    }

    public void loadCombobox() {
        dtm.setRowCount(0);
        int m = cbbMonth.getSelectedIndex();
        String y = cbbYear.getSelectedItem().toString();
        ArrayList<Statistical> list = sts.getCombobox(m, y);
        for (Statistical s : list) {
            dtm.addRow(new Object[]{s.getThang(), s.getTen(), s.getSoLuong(), s.getTongTien()});
        }
    }

    public void loadComboboxYear() {
        dtm.setRowCount(0);
        String k = cbbYear.getSelectedItem().toString();
        ArrayList<Statistical> list = sts.getComboboxYear(k);
        for (Statistical s : list) {
            dtm.addRow(new Object[]{s.getThang(), s.getTen(), s.getSoLuong(), s.getTongTien()});
        }
    }

    public void loadTableDate() {
        dtm.setRowCount(0);
        Date start_date = jDateNgayStart.getDate();
        Date end_date = jDateNgayEnd.getDate();
        ArrayList<Statistical> list = sts.getListKhoangDate(start_date, end_date);
        for (Statistical s : list) {
            dtm.addRow(new Object[]{s.getThang(), s.getTen(), s.getSoLuong(), s.getTongTien()});
        }
    }

    public void tongNam() {
        DecimalFormat x = new DecimalFormat();
        int tong = 0;
        for (int i = 0; i < tbHienThi.getRowCount(); i++) {
            tong += Integer.parseInt(tbHienThi.getValueAt(i, 3).toString());
        }
        lbNam.setText(x.format(tong) + " " + "VND");
    }

    public void tongThang() {
        DecimalFormat x = new DecimalFormat();
        int tong = 0;
        for (int i = 0; i < tbHienThi.getRowCount(); i++) {
            String p = tbHienThi.getValueAt(i, 0).toString();
            String q = tbHienThi.getValueAt(0, 0).toString();
            if (p.equals(q)) {
                tong += Integer.parseInt(tbHienThi.getValueAt(i, 3).toString());
            }
        }
        lbThang.setText(x.format(tong) + " " + "VND");
    }

    public void tongNgay() {
        DecimalFormat x = new DecimalFormat();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date start_date = jDateNgayStart.getDate();
        Date end_date = jDateNgayEnd.getDate();
        int tong = sts.sumDay(start_date, end_date);
        lbNgay.setText(x.format(tong) + " VND");
    }

    private void openExcelFile(String filePath) {
        try {
            Desktop.getDesktop().open(new File(filePath));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbThang = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbNam = new javax.swing.JLabel();
        rd1 = new javax.swing.JRadioButton();
        rd2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHienThi = new javax.swing.JTable();
        cbbMonth = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lbKhoangNgay = new javax.swing.JLabel();
        lbNgay = new javax.swing.JLabel();
        btnExcel = new app.view.swing.ButtonGradient();
        btnBieuDo = new app.view.swing.ButtonGradient();
        jDateNgayStart = new com.toedter.calendar.JDateChooser();
        jDateNgayEnd = new com.toedter.calendar.JDateChooser();
        btnTK = new app.view.swing.ButtonGradient();
        cbbYear = new javax.swing.JComboBox<>();
        btnTK1 = new app.view.swing.ButtonGradient();
        jLabel1 = new javax.swing.JLabel();
        rdTop5 = new javax.swing.JRadioButton();

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(50, 183, 163));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tổng doanh thu tháng");

        lbThang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbThang.setText("0 VND");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(lbThang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tổng doanh thu năm");

        lbNam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNam.setText("0 VND");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3)
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(lbNam)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        buttonGroup1.add(rd1);
        rd1.setSelected(true);
        rd1.setText("Biểu đồ số lượng");

        buttonGroup1.add(rd2);
        rd2.setText("Biểu đồ doanh thu");

        tbHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tháng", "Tên sản phẩm", "Số lượng bán", "Tổng tiền"
            }
        ));
        tbHienThi.setRowHeight(40);
        jScrollPane1.setViewportView(tbHienThi);

        cbbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Chọn tháng>", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMonthActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbKhoangNgay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbKhoangNgay.setText("Tổng doanh thu ngày");

        lbNgay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNgay.setText("0 VND");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lbKhoangNgay)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbKhoangNgay)
                .addGap(33, 33, 33)
                .addComponent(lbNgay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExcel.setText("Xuất file Excel");
        btnExcel.setColor2(new java.awt.Color(23, 35, 51));
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        btnBieuDo.setText("Biểu đồ");
        btnBieuDo.setColor2(new java.awt.Color(23, 35, 51));
        btnBieuDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBieuDoActionPerformed(evt);
            }
        });

        jDateNgayStart.setDateFormatString("yyyy-MM-dd");

        jDateNgayEnd.setDateFormatString("yyyy-MM-dd");

        btnTK.setText("Tìm kiếm");
        btnTK.setColor2(new java.awt.Color(23, 35, 51));
        btnTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKActionPerformed(evt);
            }
        });

        cbbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024" }));
        cbbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbYearActionPerformed(evt);
            }
        });

        btnTK1.setText("Làm Mới");
        btnTK1.setColor2(new java.awt.Color(23, 35, 51));
        btnTK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTK1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Đến");

        buttonGroup1.add(rdTop5);
        rdTop5.setText("Biểu Đồ Top 5 Sản Phẩm");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelLayout.createSequentialGroup()
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbbMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbbYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rdTop5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(35, 35, 35))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(btnBieuDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelLayout.createSequentialGroup()
                                    .addComponent(jDateNgayStart, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jDateNgayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(btnTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnTK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateNgayStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateNgayEnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(cbbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rd1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd2)
                        .addGap(12, 12, 12)
                        .addComponent(rdTop5)
                        .addGap(36, 36, 36)
                        .addComponent(btnBieuDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMonthActionPerformed
        int k = cbbMonth.getSelectedIndex();
        if (k == 0) {
            loadComboboxYear();
        } else {
            loadCombobox();
        }
    }//GEN-LAST:event_cbbMonthActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        try {
            String k = cbbYear.getSelectedItem().toString();
            ArrayList<Statistical> list = sts.getComboboxYear(k);
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheet = workbook.createSheet("BaoCaoThongKe");
            XSSFRow row = null;
            Cell cell = null;
            row = sheet.createRow(1);
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("BÁO CÁO THỐNG KÊ");
            row = sheet.createRow(3);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("Tháng");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Tên sản phẩm");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Số lượng bán");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Tổng tiền");
            if (list != null) {
                for (int i = 0; i < list.size(); i++) {
                    row = sheet.createRow(4 + i);
                    cell = row.createCell(0, CellType.STRING);
                    cell.setCellValue(list.get(i).getThang());

                    cell = row.createCell(1, CellType.STRING);
                    cell.setCellValue(list.get(i).getTen());

                    cell = row.createCell(2, CellType.STRING);
                    cell.setCellValue(list.get(i).getSoLuong());

                    cell = row.createCell(3, CellType.STRING);
                    cell.setCellValue(list.get(i).getTongTien());
                }
            }
            //            File file = new File("G:/baoCaoThongKe.xlsx");
            try {
                String file = "BaoCaoThongKeNam" + k + ".xlsx";
                FileOutputStream fis = new FileOutputStream(file);
                workbook.write(fis);
                fis.close();
                openExcelFile(file);
            } catch (FileExistsException e) {
                System.out.println("" + e.toString());
            } catch (IOException e) {
                System.out.println("" + e.toString());
            }

            JOptionPane.showMessageDialog(this, "Xuất file thành công");
        } catch (Exception e) {
            System.out.println("" + e.toString());
        }
    }//GEN-LAST:event_btnExcelActionPerformed


    private void btnBieuDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBieuDoActionPerformed
        if (rd1.isSelected()) {
            String y = cbbYear.getSelectedItem().toString();
            List<Statistical> listS = sts.getListBieuDo(y);
            if (listS != null) {
                DefaultCategoryDataset dataset = new DefaultCategoryDataset();
                for (Statistical s : listS) {
                    dataset.addValue(s.getSoLuong(), "Amount", "Tháng " + s.getThang());
                }
                JFreeChart chart = ChartFactory.createBarChart("Biểu đồ số lượng năm " + y,
                        "Thời gian", "Số lượng", dataset,
                        PlotOrientation.VERTICAL, false, true,
                        false);

                CategoryPlot categoryPlot = chart.getCategoryPlot();
                categoryPlot.setRangeGridlinePaint(Color.BLUE);

                ChartFrame ba = new ChartFrame("Biểu đồ số lượng", chart);
                ba.setVisible(true);
                ba.setLocation(300, 80);
                ba.setSize(1000, 650);
            }
            System.out.println(toString());
        }
        if (rd2.isSelected()) {
            String y = cbbYear.getSelectedItem().toString();
            List<Statistical> listS = sts.getListBieuDo(y);
            if (listS != null) {
                DefaultCategoryDataset dataset = new DefaultCategoryDataset();
                for (Statistical s : listS) {
                    dataset.addValue(s.getTongTien(), "Amount", "Tháng " + s.getThang());
                }
                JFreeChart chart = ChartFactory.createBarChart("Biểu đồ doanh thu năm " + y,
                        "Thời gian", "Doanh thu (VND)", dataset,
                        PlotOrientation.VERTICAL, false, true,
                        false);

                CategoryPlot categoryPlot = chart.getCategoryPlot();
                categoryPlot.setRangeGridlinePaint(Color.BLUE);

                ChartFrame ba = new ChartFrame("Biểu đồ doang thu", chart);
                ba.setVisible(true);
                ba.setLocation(300, 80);
                ba.setSize(1000, 650);
            }
        }

        if (rdTop5.isSelected()) {
            String y = cbbYear.getSelectedItem().toString();
            List<Statistical> listS = sts.getTop5(y);
            if (listS != null) {
                DefaultCategoryDataset dataset = new DefaultCategoryDataset();
                for (Statistical s : listS) {
                    dataset.addValue(s.getSoLuong(), "Amount", s.getTen());
                }
                JFreeChart chart = ChartFactory.createBarChart("Biểu đồ top 5 sản phẩm bán chạy nhất năm " + y,
                        "Tên sản phẩm", "Số Lượng bán", dataset,
                        PlotOrientation.VERTICAL, false, true,
                        false);

                CategoryPlot categoryPlot = chart.getCategoryPlot();
                categoryPlot.setRangeGridlinePaint(Color.BLUE);

                ChartFrame ba = new ChartFrame("Biểu đồ doang thu", chart);
                ba.setVisible(true);
                ba.setLocation(300, 80);
                ba.setSize(1000, 650);
            }
        }

    }//GEN-LAST:event_btnBieuDoActionPerformed

    private void btnTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKActionPerformed
        tongNgay();
        loadTableDate();
    }//GEN-LAST:event_btnTKActionPerformed

    private void cbbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbYearActionPerformed
        loadComboboxYear();
    }//GEN-LAST:event_cbbYearActionPerformed

    private void btnTK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTK1ActionPerformed
        loadTable();
        jDateNgayStart.setDate(null);
        jDateNgayEnd.setDate(null);
    }//GEN-LAST:event_btnTK1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.view.swing.ButtonGradient btnBieuDo;
    private app.view.swing.ButtonGradient btnExcel;
    private app.view.swing.ButtonGradient btnTK;
    private app.view.swing.ButtonGradient btnTK1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbMonth;
    private javax.swing.JComboBox<String> cbbYear;
    private com.toedter.calendar.JDateChooser jDateNgayEnd;
    private com.toedter.calendar.JDateChooser jDateNgayStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbKhoangNgay;
    private javax.swing.JLabel lbNam;
    private javax.swing.JLabel lbNgay;
    private javax.swing.JLabel lbThang;
    private javax.swing.JRadioButton rd1;
    private javax.swing.JRadioButton rd2;
    private javax.swing.JRadioButton rdTop5;
    private javax.swing.JTable tbHienThi;
    // End of variables declaration//GEN-END:variables
}
